### ISSUE TITLE
Soft Deletable doesn't work recursively

### ISSUE THREAD

**Issue by chrisShick** [CakeDC/utils#116]
I have tried and tried, but for some reason soft delete does not work recursively. I have dependent set to true in all my model. It will set delete to 1 for the one I clicked to delete, but then doesn't set any of the childrens' delete to 1.

**Comment by quest** [comment]
Hi @burzum, have you're an example of the best way to recursively delete records? I need this to my project.
Fork this repo and add this feature in develop branch, but do not know if it's the best way.

`https://github.com/quest/utils/blob/develop/Model/Behavior/SoftDeleteBehavior.php#L176`
