### ISSUE TITLE
SoftDelete deleting records ("hard delete")

### ISSUE THREAD

**Issue by jesseparker** [CakeDC/utils#134]
More of a documentation suggestion than a issue.  For the Soft Delete behaviour, the exists() function and the delete() function that you suggest to add to AppModel are required for SoftDelete to work, otherwise the records are "hard" deleted during Model->delete()

I read your docs a few times and concluded these changes weren't required, but in reality these are required.

You might just say: "For SoftDelete to work, add these functions to your AppModel"

**Comment by omnuvito** [comment]
Hi @jesseparker, thanks for your suggestion. It is already written in the documentation that these two functions are necessary for SoftDelete can work and should be added to AppModel file.

**Comment by steinkel** [comment]
hey @jesseparker does that solve your question about the documentation?

**Comment by jesseparker** [comment]
Yes - thanks.
