### ISSUE TITLE
Soft delete does not support atomic option on CakePHP 2.6+

### ISSUE THREAD

**Issue by vekakela** [CakeDC/utils#142]
CakePHP 2.6 added atomic option to the Model save -function. SoftDeleteBehavior should support this at least as an option, if people want to use transactions.

```php
return $model->save(array($model->alias => $data), false, array_keys($data));
```

becomes:

```php
return $model->save(array($model->alias => $data), array('validate' => false, 'fieldList' => array_keys($data), 'atomic' => false));
```

**Comment by Megslalk** [comment]
Hi! 
we have seen your issue. It has been passed onto our development team who will be assisting you shortly.

**Comment by andrej-griniuk** [comment]
Hi @vekakela,

This has now been implemented as "atomic" setting for SoftDeleteBehavior and merged to develop branch.

Cheers,
Andrej
