### ISSUE TITLE
ListBehavior when creating a new item

### ISSUE THREAD

**Issue by jsemander** [CakeDC/utils#144]
When I add a new item to the list, it does not give the `positionColumn` a number above `0`

This is normally when I do the following:

``` php
$this->Model->create();
$this->Model->save($this->request->data)
```

Upon looking in the code I found that by adding an else condition on `if (empty($model->data[$model->alias][$model->primaryKey])) {` to add to the bottom, it works just fine

``` php
public function beforeSave(Model $model, $options = array()) {
    extract($this->settings[$model->alias]);
    if (empty($model->data[$model->alias][$model->primaryKey])) {
        if ($addToTop) {
            $this->__addToListTop($model);
        } else {
            $this->__addToListBottom($model);
        }
-   }
+   } else {
+       $this->__addToListBottom($model);
+   }
    return true;
}
```

I do not know if there is a specific reason this is not there.

Maybe I am just not using the plugin/behavior or CakePHP right

**Comment by Megslalk** [comment]
Hi! 
we have seen your issue. It has been passed onto our development team who will be assisting you shortly.

**Comment by andrej-griniuk** [comment]
Hi @jsemander 
When you create a new item `if` condition from your code snippet should evaluate to `true`, there position column should be set. Not sure what goes wrong in your case.
With your `else` conditions it would place an item to the bottom of the list every time you update it.
Please double check your code and reopen the ticket if the problem still persists.
