### ISSUE TITLE
InheritableBehaviour: empty child data produces unexpected behaviour

### ISSUE THREAD

**Issue by ezequielp** [CakeDC/utils#57]
I reported this as a cake bug http://cakephp.lighthouseapp.com/projects/42648-cakephp/tickets/3469-saving-with-empty-fields#ticket-3469-3 which affects InheritableBehaviour 
 
On Cake 2.2.3 I have class B extends class A using CTI. 

The problem is that, if I save class B with all class B's fields empty and only setting class A fields, afterSave is not trigger and so nothing gets saved.
 
Ideally, an empty model B row should be added and then the afterSave trigger should save model A data.

**Comment by CakeDC** [comment]
Closing this one, please reopen if needed or send a PR with the unit test added. Thank you
