### ISSUE TITLE
Tree Helper to generate Twitter Bootstrap navigation 'ul' list

### ISSUE THREAD

**Issue by netstyler** [CakeDC/utils#58]
I have a threaded find result which I do pass to the helper.
The helper should help me to generate a navigation like it is shown here:
http://twitter.github.com/bootstrap/components.html#navs

CODE OUTPUT NEEDED:
http://bin.cakephp.org/view/1760699433

I tried to get it work with a node element which looks like this:
http://bin.cakephp.org/view/1056010096
Also a var_export array is given to test.

The problem is, that the vars $firstChild and $lastChild always do give me boolen true back on each child item so that I can't figure out if the child ist the last item of the dropdown menu to close it with a closing ul tag.

A other solution would be to extend the helper code to pass the needed class defintion for the nested ul list as a second argument. At the moment the main ul and li class can be defined but the list is basicly correctly generated by the helper.

**Comment by faiyazalam** [comment]
@cybercoder  thank you for sharing your code. I found the code at 
http://bakery.cakephp.org/2013/08/28/Generating-Tree-compatible-with-twitter-bootstrap-nav-subnav.html

**Comment by cybercoder** [comment]
@faiyazalam It compatibles with bootstrap 2.x only.
