### ISSUE TITLE
InheritableBehaviour fields not merged

### ISSUE THREAD

**Issue by ezequielp** [CakeDC/utils#83]
The following example:

class Person extends AppModel
{
 var $hasOne = array('Address');
}
class Client extends Person
{
  var $hasOne = array('BankAccount');
}

doesn't work correctly as Client->hasOne and Person->hasOne are not merged anywhere during model initialization (as opposed to belongTo fields). Same thing happens with hasMany.

**Comment by Megslalk** [comment]
HI! Closing this one, please reopen if still needed.
